### ISSUE TITLE
你好，想增加自定义的词典，请问词典的数据结构是怎样的？

### ISSUE THREAD

**Issue by wobuaihuangjun** [zhaoshiyu/SEANLP#5]

**Comment by zhaoshiyu** [comment]
**CoreDictionary：**
word \t POS \t weight
eg.
จอมอนิเตอร์	NCMN	13
จอรับภาพ	NCMN	1
จอสี	NCMN	5
จอเขียว	NCMN	1
จอแสดงผล	NCMN	1
จอโทรทัศน์	NCMN	1
จอโมโนโครม	NCMN	2
จะ	XVBM	4181	JSBR	9	XVAM	8	XVMM	3	NCMN	2
จะต้อง	XVMM	3

**CommonDictionary：**
word \t weight
eg.
ក	112
កក	525
កកកុញ	10
កករ	21
កកាត	5

**Comment by zhaoshiyu** [comment]
**CoreDictionary：**
word \t POS \t weight
eg.
จอมอนิเตอร์	NCMN	13
จอรับภาพ	NCMN	1
จอสี	NCMN	5
จอเขียว	NCMN	1
จอแสดงผล	NCMN	1
จอโทรทัศน์	NCMN	1
จอโมโนโครม	NCMN	2
จะ	XVBM	4181	JSBR	9	XVAM	8	XVMM	3	NCMN	2
จะต้อง	XVMM	3

**CommonDictionary：**
word \t weight
eg.
ក	112
កក	525
កកកុញ	10
កករ	21
កកាត	5

**Comment by wobuaihuangjun** [comment]
ths
